feat: 티켓 예매 API 추가 & 수정된 티켓 예매 가능시간 조회 API
DCNJ-Uket/Uket-FE pull request #37
Opened 2024-05-29 09:46 UTC by SonSuBin129

## 연관된 이슈
> ex) #36

## ✅ 작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명 해주세요(이미지 첨부 가능)
- [x] 수정된 티켓 예매 가능시간 조회 API 반영
  - 기존에 헷갈리던 id(showid, eventid, ticketingid) 등등을 수정했습니다.
- [x] 티켓 예매 API 추가

## 🚦 특이 사항
> 주의깊게 봐야하는 PR 포인트 & 말하고 싶은 점
- 예외처리에 대해서는 아직 추가하지 않았습니다.
- 티켓 예매를 실패한 경우, `/`으로 라우트하게 설정했습니다. 
이로 인해 발생하던 Stack 초기화 문제는 임의로 `pop()`으로 처리해놓은 상태입니다. 다음 issue때 수정할 예정입니다.

## 💬 리뷰 요구사항(선택)

---
🚨 **이슈를 닫아주세요!**
> ex) close #36

2024-06-01 08:18 UTC, coggiee requested changes
고생많으셨습니다! 
제가 면접 준비랑 번아웃이 동시에 와서 좀 늦었네요 죄송합니다.. ㅎㅎ........ 🥺

2024-06-01 08:18 UTC, kinwooky commented on apps/user/src/pages/home/index.tsx
>    };
함수 네이밍에 맞춰서 `handleUpdateEventId`로 변경되면 좋을 것 같습니다 ㅎㅎ

2024-06-01 08:18 UTC, kinwooky commented on apps/user/src/pages/home/_components/FestivalSection.tsx
> +  updateEventId: (id: number) => void;
props 네이밍에 맞춰서 `onUpdateEventId`로 바뀌면 좋을 것 같아요 ㅎㅎ

2024-06-01 08:18 UTC, kinwooky commented on apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
> +  const [selectedShowName, setSelectedShowName] = useState("");
`Show`와 관련한 2개의 state로 보이는데, 하나의 커스텀 훅으로 분리하는건 어떻게 생각하시나요?

2024-06-01 08:18 UTC, kinwooky commented on apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
> +  const eventId = searchParams.get("eventId");
searchParams와 관련하여 해당 코드와 아래의 `handleTicketParams`의 코드 길이가 긴 감이 없지 않아 있는 것 같습니다. 그래서 하나의 커스텀 훅으로 분리하면 좋을 것 같다는 생각이 드네요!

2024-06-01 08:18 UTC, kinwooky commented on apps/user/src/api/show.ts
>  };
react query의 `useMutation`에서 error를 반환하여 처리할 수 있어서, try-catch 구문은 없어도 될 것 같아요. 추가적으로 react-error-boundary도 설정해서 사용자 경험도 높일 수 있을 것 같네요!

2024-06-01 08:18 UTC, kinwooky commented on apps/user/src/pages/buy-ticket/_components/NextButton.tsx
>    };
`handleClick`이 서버와 통신을 수행하는 역할을 하는 것 같아서 `async-await`으로 처리해야 한다고 생각했는데, 사용하지 않은 이유가 있으실까요?

2024-06-01 08:18 UTC, kinwooky commented on apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
> +  const showId = searchParams.get("showId");
`showId`가 어디서 사용되는 건가요?! 
제가 찾지 못했을 수도 있는데 `/home`에서 `showId`가 삭제된 걸로 보았거든요!

2024-06-01 08:18 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
> +            {reservationList.map(
Suspense + Error boundary를 추가하면 사용자 경험을 더 향상시킬 수 있을 것 같아요!

현재는 일시적인 네트워크 오류나 기타 오류로 인해서 정상적인 데이터를 가져오지 못하는 경우에 사용자가 전체 페이지를 보지 못하는 문제 상황이 발생할 것 같아요.

Error boundary를 통해 에러가 발생한 컴포넌트만 예외 처리를 하고 나머지 컴포넌트는 사용자가 상호작용 가능하게 한다면 더 유연한 서비스가 될 것 같습니다!

+) 저도 `/signup`의 `index`에 `<RetryErrorBoundary>`를 잘못 선언했었는데 수정하겠습니다 ㅎㅎ..

Error boundary 관련해서 인상깊게 본 아티클이 있어서 남기고 갈게요!
https://tech.kakaopay.com/post/react-query-2/#error-boundary

2024-06-01 08:18 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
> +            {reservationList.map(
Error Boundary와 관련해서, `useQueryReservationList`는 `<ReservationList />`라는 컴포넌트에서 호출하면 좋을 것 같아요 ㅎㅎ

왜냐하면, `TimeActivity`에서 `useQuery`를 사용했을 때 에러가 발생하면 `TimeActivity`를 감싸고 있는 상위 컴포넌트인 `index.tsx`로 에러를 전달하기 때문에, 사용자가 나머지 컴포넌트와 상호작용이 불가능해지기 때문이에요. `<ReservationList />`라는 컴포넌트에서 `useQuery`를 사용한다면, 에러가 발생헀을 때 상위 컴포넌트인 `TimeActivity`로 에러를 전달하기 때문에 사용자가 나머지 컴포넌트와 상호작용을 할 수 있습니다!

러프하게 수정하면 아래와 같이 될 것 같네요 ㅎㅎ
```ts
<RetryErrorBoundary fallback...>
    <Suspense fallback...>
        <ReservationList />
    </Suspense>
</RetryErrorBoundary>
```

2024-06-01 08:18 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
> +            {reservationList.map(
그리고 `/buy-ticket`의 `index`에 `<RetryErrorBoundary />`는 삭제해도 좋을 것 같습니다 ㅎㅎ
각 라우트의 `index`에 전달되는 에러는 치명적인 에러로 간주되고, 이는 `_app.tsx`에서 `<CriticalErrorBoundary />`가 관리하고 있기 때문입니다!

```ts
const App = () => {
  const { pathname } = useLocation();
  return (
    <section className="relative flex h-dvh w-screen flex-col">
      <CriticalErrorBoundary>
        {!["/", "/ticket-detail"].includes(pathname) && (
          <header className="sticky left-0 top-0 z-10 bg-white">
            <Nav />
          </header>
        )}
        <main className="w-full grow">
          <Outlet />
        </main>
      </CriticalErrorBoundary>
    </section>
  );
};
```

2024-06-01 08:18 UTC, coggiee commented on apps/user/src/api/show.ts
> +    });
`Authorization`은 현재 axios instance로 관리하고 있고 axios 호출 시 자동으로 설정되기 때문에 따로 추가하지 않으셔도 됩니다!

```ts
// /api/instance.ts
const AUTH_REQUIRED_PATH = ["/users/register", "/users/info"];

// code ...

instance.interceptors.request.use(config => {
  if (config.url && AUTH_REQUIRED_PATH.includes(config.url)) {
    const accessToken = getAccessToken();

    config.headers.Authorization = `Bearer ${accessToken}`;
  }

  return config;
});
```
**다만, `AUTH_REQUIRED_PATH`에 `/tickets`를 추가하셔야 합니닷!**

2024-06-02 11:12 UTC, SonSuBin129 commented on apps/user/src/pages/buy-ticket/_components/NextButton.tsx
>    };
어엇, 원래 그렇게 작성했었는데, 제가 pop 때문에 이것저것 시도하다가 누락해버렸네요! 반영하겠습니다!!

2024-06-02 11:16 UTC, SonSuBin129 commented on apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
> +  const showId = searchParams.get("showId");
DateActivity에서 사용됩니다!
`/home`에서 `eventId` 넘겨주면, 티켓 예매(날짜 선택)에서 `showId`를 parameter로 설정하고, 티켓예매(시간선택)에서 `reservationId`를 가지고 백엔드와 통신합니다!

백엔드 api 변경된 김에 id명을 바꿨습니다!

2024-06-03 14:51 UTC, SonSuBin129 commented
fallback 디자인은 아직 반영하지 못했습니다!
comment 기반으로 전반적으로 수정해봤는데 확인 부탁드립니다 :)

2024-06-04 04:39 UTC, coggiee approved these changes

2024-06-04 04:40 UTC, merged