style: 회원정보 조회 페이지 레이아웃 구현
DCNJ-Uket/Uket-FE pull request #57
Opened 2024-06-26 16:06 UTC by SonSuBin129

## 연관된 이슈
> ex) #54

## ✅ 작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명 해주세요(이미지 첨부 가능)
- [x] 회원정보 조회 페이지 레이아웃 구현
- [x] 뒤로가기 버튼 수정

## 🚦 특이 사항
> 주의깊게 봐야하는 PR 포인트 & 말하고 싶은 점
- 푸시알람과 회원탈퇴 기능은 아직 추가하지 않았습니다.
   - 푸시알람은 금주 회의때 정해지는 대로 추가할 예정입니다.
- `/home`과 `landing`페이지 외에 `Nav`바가 사용되지 않는 것을 고려해서 `BackNav`를 만들어서 `app.tsx`에서 조건문을 통해 보여지도록 수정했습니다.

## 💬 리뷰 요구사항(선택)

---
🚨 **이슈를 닫아주세요!**
> ex) close #54

2024-06-27 01:41 UTC, coggiee requested changes
고생하셨습니다~! 👍
`usePreviousPath` 인상깊게 봤습니다 ㅎㅎ
몇 가지 사소한 의견이랑 변경되면 좋을 것 같은 부분 코멘트 달았습니다!

2024-06-27 01:41 UTC, coggiee commented on apps/user/src/components/Nav.tsx
`BackNav`를 사용하는 대신에, `Nav` 컴포넌트만으로 뒤로가기를 제어하면 유지보수 비용도 절감할 수 있고 무엇보다도 네비게이션이라는 역할을 명확히 하나로만 줄일 수 있을 것 같아요!

```ts
import { Link, useLocation } from "react-router-dom";
import { FallbackProps } from "react-error-boundary";
import { cn } from "@uket/ui/lib/utils";
import { IconBack } from "@stackflow/plugin-basic-ui";

import usePreviousPath from "@/hooks/usePreviousPath";

import Profile from "./Profile";
import Logo from "./Logo";
import LoginErrorFallback from "./fallback/LoginErrorFallback";
import RetryErrorBoundary from "./error/RetryErrorBoundary";

const Nav = () => {
  const { pathname } = useLocation();
  const previousPath = usePreviousPath();

  return (
    <nav className="container my-2 flex h-10 w-full items-center justify-between self-stretch">
      {["/", "/home"].includes(pathname) ? (
        <>
          <Logo />
          <RetryErrorBoundary
            resetKeys={["user-info"]}
            fallbackComponent={(props: FallbackProps) => (
              <LoginErrorFallback
                className={cn("text-black", pathname === "/" && "text-white")}
                {...props}
              />
            )}
          >
            <Profile />
          </RetryErrorBoundary>
        </>
      ) : (
        <Link to={previousPath}>
          <IconBack />
        </Link>
      )}
    </nav>
  );
};

export default Nav;

```

2024-06-27 01:41 UTC, coggiee commented on apps/user/src/hooks/usePreviousPath.ts
다양한 곳에서 쓰일 수 있을 것 같네요 👍

2024-06-27 01:41 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/CompleteActivity.tsx
> +    <AppScreen
`height`는 어떤 목적이 따로 있는건가요??

2024-06-27 01:41 UTC, coggiee commented on apps/user/src/pages/_app.tsx
위의 `Nav` 코멘트에 이어서 `_app.tsx`도 아래와 같이 바꾸면 하나의 `Nav`만으로 네비게이션을 제어할 수 있을 것 같슴다!
```tsx
import { Outlet, useLocation } from "react-router-dom";

import Nav from "@/components/Nav";
import CriticalErrorBoundary from "@/components/error/CriticalErrorBoundary";

import Redirects from "@/utils/redirects";

const App = () => {
  const { pathname } = useLocation();
  
  return (
    <CriticalErrorBoundary>
      <section className="relative flex h-dvh w-screen flex-col">
        {!["/"].includes(pathname) && (
          <header className="sticky left-0 top-0 z-10 bg-white">
            <Nav />
          </header>
        )}
        <main className="w-full grow">
          <Redirects>
            <Outlet />
          </Redirects>
        </main>
      </section>
    </CriticalErrorBoundary>
  );
};

export default App;

```

2024-06-27 01:41 UTC, coggiee commented on package.json
> +  },
`ui/package.json`에 설치가 되어야 하는데 잘못 설치된 것 같습니다. 제거 부탁드릴게요!

2024-06-27 01:41 UTC, coggiee commented on pnpm-lock.yaml
> +        version: 1.1.0(@types/react-dom@18.3.0)(@types/react@18.3.2)(react-dom@18.3.1(react@18.3.1))(react@18.3.1)
여기도 `package.json`에 이어서 제거 부탁드립니다~!

2024-06-27 01:41 UTC, coggiee commented on apps/user/src/pages/myinfo/_components/LogoutModal.tsx
> +  const onLogout = props.onLogout;
`const { onLogout } = props;`로 수정부탁드립니다~!

2024-06-27 01:41 UTC, coggiee commented on apps/user/src/pages/myinfo/_components/LogoutModal.tsx
> +      )}
로그아웃이 완료되었다는 모달을 띄우는 건 약간 과한것 같다는 개인적인 생각이 들었는데, 수빈님은 어떻게 생각하시는지 궁금해요.
저는 간단하게 [Toast](https://ui.shadcn.com/docs/components/toast)로만 표현해도 될 것 같거든요 ㅎㅎ..

이건 아직 디자인 완성본이 나오지 않아서 드리는 제 사소한 의견이니 참고만 해주세요!
코드에 대한 의견은 아닙니다!!

2024-06-27 01:41 UTC, coggiee commented on apps/user/src/pages/myinfo/_components/InfoItem.tsx
> +  content: string;
`string` 타입이 아닌, 유저 정보 조회 API를 통해 반환된 `response`의 타입으로 바꾸면, 타입이 더 안정될 것 같습니다!

2024-06-27 01:41 UTC, coggiee commented on apps/user/src/pages/myinfo/index.tsx
현재는 오류가 발생하면 사용자가 페이지 전체를 보지 못하게 되고, 만약 유저정보가 `null`이라면 사용자 입장에서 페이지가 로딩 중인지, 정보가 없는건지 구분할 수 없을 것 같아요.
그래서 `useQueryUserInfo()`의 오류를 처리할 수 있는 `RetryErrorBoundary`를 추가해서 Root로 에러가 전파되는 걸 막고 다시시도 버튼을 노출해서, 사용자 정보를 다시 받아올 수 있게 하면 더 좋을 것 같습니다!

2024-06-27 04:36 UTC, SonSuBin129 commented on apps/user/src/pages/buy-ticket/_components/CompleteActivity.tsx
> +    <AppScreen
아! 이걸 없앴을때, 기존 Navbar랑 높이가 다르더라구요, 그래서 맞춰놨었어요!

2024-06-27 04:37 UTC, SonSuBin129 commented on apps/user/src/pages/myinfo/_components/LogoutModal.tsx
> +      )}
아! 저도 이거에 대해서 비슷하게 생각하는데, 일단 어떻게 될지 몰라서 미리 만들어봤어요! 이번주 회의때 한번 얘기해보는 것도 좋을 것 같습니다!!

2024-06-27 05:02 UTC, SonSuBin129 commented on apps/user/src/pages/myinfo/_components/InfoItem.tsx
> +  content: string;
`interface InfoItemProps {
  title: string;
  content: string | number | boolean;
}

const InfoItem = (props: InfoItemProps) => {
  const { title, content } = props;

  let displayContent: string;
  if (typeof content === 'boolean') {
    displayContent = content ? 'Yes' : 'No';
  } else {
    displayContent = content.toString();
  }

  return (
    <div className="grid w-full grid-cols-2 text-xs font-semibold">
      <p className="text-[#5A5A5A]">{title}</p>
      <p>{displayContent}</p>
    </div>
  );
};`

혹시 말씀하신게 이런 방식이 맞을까요?

2024-06-27 05:07 UTC, SonSuBin129 commented on apps/user/src/pages/myinfo/_components/InfoItem.tsx
> +  content: string;
```
interface InfoItemProps {
  title: string;
  content: string | number | boolean;
}

const InfoItem = (props: InfoItemProps) => {
  const { title, content } = props;

  let displayContent: string;
  if (typeof content === 'boolean') {
    displayContent = content ? 'Yes' : 'No';
  } else {
    displayContent = content.toString();
  }

  return (
    <div className="grid w-full grid-cols-2 text-xs font-semibold">
      <p className="text-[#5A5A5A]">{title}</p>
      <p>{displayContent}</p>
    </div>
  );
};
```

말씀하신게 이런 느낌이 맞을까요?? 지금 현재 유저정보조회 반환 `response`에는 `string`, `boolean`, `number`만 있는 상황입니다!

2024-06-27 05:16 UTC, coggiee commented on apps/user/src/pages/myinfo/_components/InfoItem.tsx
> +  content: string;
제가 생각한 건 `Partial<UserInfoResponse>` 이런 느낌이었어요!

2024-06-27 05:21 UTC, SonSuBin129 commented on apps/user/src/pages/myinfo/_components/InfoItem.tsx
> +  content: string;
아하! 알겠습니당!

2024-06-27 07:21 UTC, SonSuBin129 commented
회원 정보 조회하는 부분은 전에 Ticket 컴포넌트 추상화를 감명깊게 봤던 기억이 있어서, 반영해서 수정해봤습니다!
`InfoSection`에서 `GeneralInfo`, `UnivInfo`로 나누었습니다.
이 방식도 괜찮다고 하시면, `InfoSection.tsx`는 삭제하고 진행하겠습니다!
다른 코멘트 있으면 말씀해주세요!

2024-06-28 02:27 UTC, coggiee commented on apps/user/src/pages/myinfo/index.tsx
>          </main>
고생하셨습니다 ㅎㅎ 이전 리뷰에서 미처 보지 못했던 부분이 2가지 정도 있어서 살짝 언급하고 가겠슴돠..ㅎㅎ
1. `userInfo && ...` 코드의 불필요함
  - `Suspense`가 데이터가 올 때 까지 일종의 대기하는 역할이기 때문에, 데이터가 항상 보여진다고 보장할 수 있어요! 그래서 삭제해도 될 것 같습니다 ㅎㅎ
2. `ErrorBoundary`가 에러를 포착하지 못함
  - 현재 페이지에서 `useQueryUserInfo`를 사용하고 있어요. 여기서 에러가 발생하면 `RetryErrorBoundary`에서 에러를 포착하는게 아닌 Root로 에러가 전파되어서 `CriticalErrorBoundary`에서 포착될 거에요! `CriticalErrorBoundary`는 500 에러만 포착하는 역할을 하기 때문에, `useQueryUserInfo`에서 반환받은 데이터를 사용하는 컴포넌트를 따로 생성해야 에러를 정상적으로 포착할 수 있을 것 같습니다!

2024-06-28 02:33 UTC, coggiee commented on apps/user/src/pages/myinfo/index.tsx
> +                />
사용자 구분은 비워두신게 맞을까요?!

2024-06-28 02:42 UTC, SonSuBin129 commented on apps/user/src/pages/myinfo/index.tsx
> +                />
아 어제 영준님이 추가하시고, UnivInfo만 추가하고 GeneralInfo에는 추가를 안했네요! 수정하겠습니당

2024-06-28 06:59 UTC, coggiee commented on apps/user/src/pages/myinfo/_components/UserInfoSection.tsx
> +  if (userInfo === null) {
데이터가 성공적으로 보내진다면 데이터는 `null`이 될 수 없고 에러로 인해 보내지지 않는다면 `useQuery`에서 에러를 전파하기 때문에 `userInfo === null` 없어도 될 것 같아요!

2024-06-28 06:59 UTC, coggiee approved these changes

2024-06-28 07:28 UTC, SonSuBin129 commented on apps/user/src/pages/myinfo/_components/UserInfoSection.tsx
> +  if (userInfo === null) {
```
/* eslint-disable react-hooks/rules-of-hooks */
import { useSuspenseQuery } from "@tanstack/react-query";

import { UserInfoResponse } from "@/types/userType";

import { getAccessToken } from "@/utils/handleToken";
import { getRefreshToken } from "@/utils/handleCookie";

import { getUserInfo } from "@/api/user";

export const useQueryUserInfo = () => {
  const accessToken = getAccessToken();
  const refreshToken = getRefreshToken("refreshToken");

  if (!accessToken || !refreshToken) return { data: null };

  const { data, error } = useSuspenseQuery<UserInfoResponse>({
    queryKey: ["user-info"],
    queryFn: () => getUserInfo(),
    refetchOnMount: true,
    refetchOnWindowFocus: true,
  });

  if (error) {
    throw error;
  }

  return { data: data || null };
};
```

`useQueryUserInfo.ts`에서 null을 반환하는 경우도 있어서 RetryErrorBoundary로 막아줄 필요가 있었던거 아닌가요?

2024-06-28 10:54 UTC, merged