style: 티켓 예매 스타일 수정
DCNJ-Uket/Uket-FE pull request #68
Opened 2024-07-08 09:31 UTC by SonSuBin129

## 연관된 이슈
> ex) #67

## ✅ 작업 내용
> 이번 PR에서 작업한 내용을 간략히 설명 해주세요(이미지 첨부 가능)
- [x] 티켓 예매 스타일 수정
   - [x] soldout 디자인 추가
   - [x] 티켓 가능 시간대에 따른 디자인 수정
- [x] 변경된 api 수정

## 🚦 특이 사항
> 주의깊게 봐야하는 PR 포인트 & 말하고 싶은 점
- 현재 디자인에 맞춰서 에러 fallback에 로고 이미지를 넣어서 `BuyTicketErrorFallback.tsx`를 추가해봤습니다.
- 티켓 구매 페이지에 공통된 요소가 많아서 추상화를 진행해봤습니다. 더 좋은 방향이 있다면 피드백 남겨주세요!
- 티켓 예매 가능 시각이 아닌 경우의 디자인은 아직 반영되지 않았습니다. 디자인 반영된 후에 추가하겠습니다.

## 💬 리뷰 요구사항(선택)

---
🚨 **이슈를 닫아주세요!**
> ex) close #67

2024-07-08 11:34 UTC, coggiee requested changes
수고하셨습니다 수빈님 ㅎㅎ
몇 가지 코멘트 남겼으니 확인 부탁드립니다~!

2024-07-08 11:34 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
>    };
`handleSelectReservation`이 `selectedStartTime, selectedEndTime`과 관련이 있는 함수여서, `useReservationSelection`에 묶어서 커스텀 훅으로 작성하는 것도 좋아보입니다.

2024-07-08 11:34 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/TimeActivity.tsx
> +          />
기존의 `RetryErrorBoundary`가 삭제되면 API 응답 오류가 발생할 경우 에러가 화면 전체를 덮어서, 사용자가 어떤 동작도 하지 못하게 될 것 같아요. UX 관점에서는 `RetryErrorBoundary`가 있으면 좋을 것 같습니다!

2024-07-08 11:34 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
> +  const { reservationUserType, shows } = data;
해당 커스텀 쿼리 훅을 이곳으로 옮긴 이유가 있을까요?
`RetryErrorBoundary`도 삭제되었는데, `TimeActivity`에 언급했던 이유로 인해 필요해 보입니다.

2024-07-08 11:34 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/DateItem.tsx
빈 라인은 없으면 좋을 것 같습니다!

2024-07-08 11:34 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/ShowList.tsx
이 부분도 기존의 `useQueryShowList`의 호출 위치를 변경한 이유가 있으실까요?

2024-07-08 11:34 UTC, coggiee commented on apps/user/src/pages/buy-ticket/_components/TimeItem.tsx
> +        <TicketFooter>
빈 라인은 없어도 될 것 같습니다!

2024-07-08 11:34 UTC, coggiee commented on apps/user/src/types/showType.ts
> +  reservationUserType: string;
가능하다면 추후에 `string` 타입이 아닌, '일반인' | '자대생' 이런식으로 변경되면 좋을 것 같습니다.
현재 백엔드 측에서 swagger의 스키마에 정확히 명시해준 부분이 없어서, 말씀 드려보면 좋을 것 같아요 ㅎㅎ

2024-07-08 11:53 UTC, SonSuBin129 commented on apps/user/src/pages/buy-ticket/_components/ShowList.tsx
백엔드 측 변경된 api에서 `reservationUserType`이라는 필드를 같이 보내는데요, 이게 "자대생 Zon, 일반인 Zone" 의 값을 가지고 있습니다. 디자인에 따르면,  이 부분은 DateActivity 상단에 노출되어야하는 부분이라서 `ShowList.tsx`에서 호출하지 않고 `DateActivity.tsx`에서 호출하도록 변경했습니다.

2024-07-08 11:54 UTC, SonSuBin129 commented on apps/user/src/pages/buy-ticket/_components/DateActivity.tsx
> +  const { reservationUserType, shows } = data;
api가 변경되면서 api 호출위치가 DateActivity로 옮겨져야한다고 판단했고, 그래서 `RetryErrorBoundary`를 `index.tsx` 부분에 감쌌습니다!

2024-07-09 00:18 UTC, coggiee approved these changes

2024-07-09 02:33 UTC, merged